steps:
  # Build the orchestrator image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/orchestrator', '-f', 'orchestrator/Dockerfile', '.' ]

  # Build the requirements-review-agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/requirements-review-agent', '-f', 'agents/requirements_review/Dockerfile', '.' ]

  # Build the test-case-generation-agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test-case-generation-agent', '-f', 'agents/test_case_generation/Dockerfile', '.' ]

  # Build the test-case-classification-agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test-case-classification-agent', '-f', 'agents/test_case_classification/Dockerfile', '.' ]

  # Build the test-case-review-agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test-case-review-agent', '-f', 'agents/test_case_review/Dockerfile', '.' ]

  # Push the images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/orchestrator' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/requirements-review-agent' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test-case-generation-agent' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test-case-classification-agent' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test-case-review-agent' ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'jira-mcp-server'
      - '--image=mcp/atlassian:latest'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--ingress=internal'
      - '--vpc-egress=private-ranges-only'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--max-instances=1'
      - '--set-secrets=JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,JIRA_URL=JIRA_URL:latest'
      - '--port=9000'
      - '--args=--transport,sse,--port,9000,-vv'
      - '--add-volume=type=cloud-storage,name=jira-volume,bucket=$_BUCKET_NAME,mount-options=only-dir=$_JIRA_ATTACHMENTS_FOLDER'
      - '--add-volume-mount=volume=jira-volume,mount-path=/tmp'
      - '--concurrency=5'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'orchestrator'
      - '--image=gcr.io/$PROJECT_ID/orchestrator'
      - '--platform=managed'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--vpc-egress=all-traffic'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--max-instances=1'
      - '--concurrency=1'
      - '--set-env-vars=^;^REMOTE_EXECUTION_AGENT_HOSTS=$_REMOTE_EXECUTION_AGENT_HOSTS'
      - '--set-env-vars=AGENT_DISCOVERY_PORTS=443-443,GOOGLE_CLOUD_LOGGING_ENABLED=true,USE_CLOUD_STORAGE=true,CLOUD_STORAGE_BUCKET_NAME=$_BUCKET_NAME,JIRA_ATTACHMENTS_CLOUD_STORAGE_FOLDER=$_JIRA_ATTACHMENTS_FOLDER'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,ZEPHYR_API_TOKEN=ZEPHYR_API_TOKEN:latest,JIRA_URL=JIRA_URL:latest,ZEPHYR_BASE_URL=ZEPHYR_BASE_URL:latest,ORCHESTRATOR_API_KEY=ORCHESTRATOR_API_KEY:latest'
      - '--add-volume=type=cloud-storage,name=gcs-allure-reports,bucket=$_ALLURE_REPORTS_BUCKET'
      - '--add-volume-mount=volume=gcs-allure-reports,mount-path=$_ALLURE_REPORTS_CONTAINER_PATH'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'requirements-review-agent'
      - '--image=gcr.io/$PROJECT_ID/requirements-review-agent'
      - '--platform=managed'
      - '--ingress=internal'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--vpc-egress=all-traffic'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--max-instances=1'
      - '--concurrency=1'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,ZEPHYR_API_TOKEN=ZEPHYR_API_TOKEN:latest,JIRA_URL=JIRA_URL:latest,JIRA_MCP_SERVER_URL=JIRA_MCP_SERVER_URL:latest,ZEPHYR_BASE_URL=ZEPHYR_BASE_URL:latest'
      - '--set-env-vars=USE_CLOUD_STORAGE=true,GOOGLE_CLOUD_LOGGING_ENABLED=true,AGENT_BASE_URL=$_REQUIREMENTS_REVIEW_AGENT_BASE_URL,CLOUD_STORAGE_BUCKET_NAME=$_BUCKET_NAME,JIRA_ATTACHMENTS_CLOUD_STORAGE_FOLDER=$_JIRA_ATTACHMENTS_FOLDER'
      - '--port=8001'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'test-case-generation-agent'
      - '--image=gcr.io/$PROJECT_ID/test-case-generation-agent'
      - '--platform=managed'
      - '--ingress=internal'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--vpc-egress=all-traffic'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--max-instances=1'
      - '--concurrency=1'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,ZEPHYR_API_TOKEN=ZEPHYR_API_TOKEN:latest,JIRA_URL=JIRA_URL:latest,JIRA_MCP_SERVER_URL=JIRA_MCP_SERVER_URL:latest,ZEPHYR_BASE_URL=ZEPHYR_BASE_URL:latest'
      - '--set-env-vars=USE_CLOUD_STORAGE=true,GOOGLE_CLOUD_LOGGING_ENABLED=true,AGENT_BASE_URL=$_TEST_CASE_GENERATION_AGENT_BASE_URL,CLOUD_STORAGE_BUCKET_NAME=$_BUCKET_NAME,JIRA_ATTACHMENTS_CLOUD_STORAGE_FOLDER=$_JIRA_ATTACHMENTS_FOLDER'
      - '--port=8001'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'test-case-classification-agent'
      - '--image=gcr.io/$PROJECT_ID/test-case-classification-agent'
      - '--platform=managed'
      - '--ingress=internal'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--vpc-egress=all-traffic'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--max-instances=1'
      - '--concurrency=1'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,ZEPHYR_API_TOKEN=ZEPHYR_API_TOKEN:latest,JIRA_URL=JIRA_URL:latest,JIRA_MCP_SERVER_URL=JIRA_MCP_SERVER_URL:latest,ZEPHYR_BASE_URL=ZEPHYR_BASE_URL:latest'
      - '--set-env-vars=USE_CLOUD_STORAGE=true,GOOGLE_CLOUD_LOGGING_ENABLED=true,AGENT_BASE_URL=$_TEST_CASE_CLASSIFICATION_AGENT_BASE_URL,CLOUD_STORAGE_BUCKET_NAME=$_BUCKET_NAME,JIRA_ATTACHMENTS_CLOUD_STORAGE_FOLDER=$_JIRA_ATTACHMENTS_FOLDER'
      - '--port=8001'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'test-case-review-agent'
      - '--image=gcr.io/$PROJECT_ID/test-case-review-agent'
      - '--platform=managed'
      - '--ingress=internal'
      - '--network=agent-network'
      - '--subnet=agent-network'
      - '--vpc-egress=all-traffic'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--max-instances=1'
      - '--concurrency=1'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,JIRA_USERNAME=JIRA_USERNAME:latest,ZEPHYR_API_TOKEN=ZEPHYR_API_TOKEN:latest,JIRA_URL=JIRA_URL:latest,JIRA_MCP_SERVER_URL=JIRA_MCP_SERVER_URL:latest,ZEPHYR_BASE_URL=ZEPHYR_BASE_URL:latest'
      - '--set-env-vars=USE_CLOUD_STORAGE=true,GOOGLE_CLOUD_LOGGING_ENABLED=true,AGENT_BASE_URL=$_TEST_CASE_REVIEW_AGENT_BASE_URL,CLOUD_STORAGE_BUCKET_NAME=$_BUCKET_NAME,JIRA_ATTACHMENTS_CLOUD_STORAGE_FOLDER=$_JIRA_ATTACHMENTS_FOLDER'
      - '--port=8001'

substitutions:
  _JIRA_ATTACHMENTS_FOLDER: 'jira'
  _BUCKET_NAME: ''
  _ALLURE_REPORTS_CONTAINER_PATH: '/app/allure-report'
  _ALLURE_REPORTS_BUCKET: ''
  _REMOTE_EXECUTION_AGENT_HOSTS: ''
  _REQUIREMENTS_REVIEW_AGENT_BASE_URL: ''
  _TEST_CASE_CLASSIFICATION_AGENT_BASE_URL: ''
  _TEST_CASE_GENERATION_AGENT_BASE_URL: ''
  _TEST_CASE_REVIEW_AGENT_BASE_URL: ''

images:
  - 'gcr.io/$PROJECT_ID/requirements-review-agent'
  - 'gcr.io/$PROJECT_ID/test-case-generation-agent'
  - 'gcr.io/$PROJECT_ID/test-case-classification-agent'
  - 'gcr.io/$PROJECT_ID/test-case-review-agent'
  - 'gcr.io/$PROJECT_ID/orchestrator'